# Generated by Django 5.2 on 2025-12-09 19:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComunicateEmergencyDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_communications', to='department.department')),
            ],
            options={
                'verbose_name': 'Emergency Department Communication',
                'verbose_name_plural': 'Emergency Department Communications',
                'db_table': 'comunicate_emergency_department',
            },
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('code_emergency', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('emergency_status', models.CharField(choices=[('open', 'Open'), ('standby', 'Standby'), ('in_progress', 'In Progress'), ('close', 'Close')], default='open', max_length=20)),
                ('type_emergency', models.CharField(choices=[('vehicular_accident', 'Accident'), ('sanitary_assistance', 'Sanitary Assistance'), ('Fire', 'Fire')], default='sanitary_assistance', max_length=20)),
                ('subtype_emergency', models.CharField(blank=True, max_length=100, null=True)),
                ('date_open', models.DateTimeField(blank=True, null=True)),
                ('date_standby', models.DateTimeField(blank=True, null=True)),
                ('date_in_progress', models.DateTimeField(blank=True, null=True)),
                ('date_close', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the emergency', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_emergencies', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(related_name='emergencies', through='emergency.ComunicateEmergencyDepartment', to='department.department')),
                ('emergency_main', models.ForeignKey(blank=True, help_text='Main emergency if this is a sub-emergency', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_emergencies', to='emergency.emergency')),
            ],
            options={
                'verbose_name': 'Emergency',
                'verbose_name_plural': 'Emergencies',
                'db_table': 'emergency',
                'ordering': ['-date_time'],
            },
        ),
        migrations.AddField(
            model_name='comunicateemergencydepartment',
            name='code_emergency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_communications', to='emergency.emergency'),
        ),
        migrations.AlterUniqueTogether(
            name='comunicateemergencydepartment',
            unique_together={('code_emergency', 'code_department')},
        ),
    ]
