# Generated by Django 5.2 on 2025-09-25 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicateEmergencyDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_close', models.BooleanField(default=False)),
                ('code_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_communications', to='department.department')),
            ],
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('code_emergency', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_by', models.ForeignKey(default=10000001, on_delete=django.db.models.deletion.CASCADE, related_name='related_users', to=settings.AUTH_USER_MODEL)),
                ('department', models.ManyToManyField(related_name='Emergency_Department', through='emergency.CommunicateEmergencyDepartment', to='department.department')),
                ('emergency_main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_emergencies', to='emergency.emergency')),
            ],
        ),
        migrations.AddField(
            model_name='communicateemergencydepartment',
            name='code_emergency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_communications', to='emergency.emergency'),
        ),
    ]
