# Generated by Django 5.2 on 2025-09-18 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
        ('users', '0002_allergy_chronicdisease_disability_previoussurgery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='created_by',
            field=models.ForeignKey(default=10000001, on_delete=django.db.models.deletion.CASCADE, related_name='related_users', to='users.user'),
        ),
    ]
