# Generated by Django 5.2 on 2025-09-25 19:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Allergy',
                'verbose_name_plural': 'Allergies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChronicDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chronic Disease',
                'verbose_name_plural': 'Chronic Diseases',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Disability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Disability',
                'verbose_name_plural': 'Disabilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PreviousSurgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Previous Surgery',
                'verbose_name_plural': 'Previous Surgeries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('google_id', models.CharField(blank=True, help_text='Unique Google ID for OAuth users', max_length=255, null=True, unique=True)),
                ('is_oauth_user', models.BooleanField(default=False, help_text='Indicates if user registered with OAuth')),
                ('identificator', models.BigIntegerField(blank=True, help_text='DNI, passport or other identity document number', null=True)),
                ('address', models.CharField(blank=True, help_text="User's address", max_length=100, null=True)),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Prefer not to say')], max_length=1, null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Height in centimeters', null=True)),
                ('weight', models.PositiveIntegerField(blank=True, help_text='Weight in kilograms', null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('allergies_other', models.TextField(blank=True, help_text='Other allergies not in predefined list', null=True)),
                ('chronic_diseases_other', models.TextField(blank=True, help_text='Other chronic diseases not in predefined list', null=True)),
                ('previous_surgeries_other', models.TextField(blank=True, help_text='Other previous surgeries not in predefined list', null=True)),
                ('disabilities_other', models.TextField(blank=True, help_text='Other disabilities not in predefined list', null=True)),
                ('close_contacts', models.JSONField(default=dict, help_text='Emergency contacts in JSON format')),
                ('phone_number', models.PositiveBigIntegerField(blank=True, help_text='Phone number as positive integer', null=True)),
                ('strikes', models.PositiveIntegerField(default=0, help_text='Number of warnings or infractions')),
                ('blocked', models.BooleanField(default=False, help_text='Indicates if user is blocked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('allergies', models.ManyToManyField(blank=True, help_text='Predefined allergy options', related_name='users_with_allergy', to='users.allergy')),
                ('chronic_diseases', models.ManyToManyField(blank=True, help_text='Predefined chronic disease options', related_name='users_with_disease', to='users.chronicdisease')),
                ('disabilities', models.ManyToManyField(blank=True, help_text='Predefined disability options', related_name='users_with_disability', to='users.disability')),
                ('previous_surgeries', models.ManyToManyField(blank=True, help_text='Predefined previous surgery options', related_name='users_with_surgery', to='users.previoussurgery')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
