# Generated by Django 5.2 on 2025-04-30 23:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)])),
                ('name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Prefere not to say')], max_length=1)),
                ('height_cm', models.PositiveIntegerField()),
                ('weight_kg', models.PositiveIntegerField()),
                ('age', models.PositiveIntegerField()),
                ('allergies', models.TextField(blank=True)),
                ('chronic_diseases', models.TextField(blank=True)),
                ('previous_surgeries', models.TextField(blank=True)),
                ('disabilities', models.TextField(blank=True)),
                ('close_contacts', models.JSONField(default=dict)),
            ],
        ),
    ]
