# Generated by Django 5.2 on 2025-09-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Allergy',
                'verbose_name_plural': 'Allergies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChronicDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chronic Disease',
                'verbose_name_plural': 'Chronic Diseases',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Disability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Disability',
                'verbose_name_plural': 'Disabilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PreviousSurgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Previous Surgery',
                'verbose_name_plural': 'Previous Surgeries',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='usercustom',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usercustom',
            name='user_permissions',
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('google_id', models.CharField(blank=True, help_text='Unique Google ID for OAuth users', max_length=255, null=True, unique=True)),
                ('is_oauth_user', models.BooleanField(default=False, help_text='Indicates if user registered with OAuth')),
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('identificator', models.BigIntegerField(blank=True, help_text='DNI, passport or other identity document number', null=True)),
                ('address', models.CharField(blank=True, help_text="User's address", max_length=100, null=True)),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Prefer not to say')], max_length=1, null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Height in centimeters', null=True)),
                ('weight', models.PositiveIntegerField(blank=True, help_text='Weight in kilograms', null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('allergies_other', models.TextField(blank=True, help_text='Other allergies not in predefined list', null=True)),
                ('chronic_diseases_other', models.TextField(blank=True, help_text='Other chronic diseases not in predefined list', null=True)),
                ('previous_surgeries_other', models.TextField(blank=True, help_text='Other previous surgeries not in predefined list', null=True)),
                ('disabilities_other', models.TextField(blank=True, help_text='Other disabilities not in predefined list', null=True)),
                ('close_contacts', models.JSONField(default=dict, help_text='Emergency contacts in JSON format')),
                ('phone_number', models.PositiveBigIntegerField(blank=True, help_text='Phone number as positive integer', null=True)),
                ('strikes', models.PositiveIntegerField(default=0, help_text='Number of warnings or infractions')),
                ('blocked', models.BooleanField(default=False, help_text='Indicates if user is blocked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allergies', models.ManyToManyField(blank=True, help_text='Predefined allergy options', related_name='users_with_allergy', to='users.allergy')),
                ('chronic_diseases', models.ManyToManyField(blank=True, help_text='Predefined chronic disease options', related_name='users_with_disease', to='users.chronicdisease')),
                ('disabilities', models.ManyToManyField(blank=True, help_text='Predefined disability options', related_name='users_with_disability', to='users.disability')),
                ('previous_surgeries', models.ManyToManyField(blank=True, help_text='Predefined previous surgery options', related_name='users_with_surgery', to='users.previoussurgery')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
            },
        ),
    ]
