# Generated by Django 5.2 on 2025-09-18 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_alter_emergency_created_by'),
        ('users', '0002_allergy_chronicdisease_disability_previoussurgery_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCustom',
        ),
    ]
