# Generated by Django 5.2 on 2025-12-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_age_user_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='close_contacts',
            field=models.JSONField(blank=True, default=dict, help_text='Emergency contacts in JSON format', null=True),
        ),
    ]
