# Generated by Django 5.2 on 2025-04-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code_department', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('type_department', models.CharField(choices=[('F', 'Firefighters'), ('P', 'Police')], max_length=1)),
                ('name_department', models.CharField(max_length=50)),
                ('jurisdiction', models.JSONField()),
                ('city_center_lat', models.FloatField()),
                ('city_center_lon', models.FloatField()),
                ('phone', models.BigIntegerField()),
            ],
        ),
    ]
