# Generated by Django 5.2 on 2025-12-09 20:25

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code_department', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.PositiveBigIntegerField(blank=True, help_text='Phone number as positive integer', null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('jurisdiction', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text="GeoJSON polygon representing the department's jurisdiction", null=True, srid=4326)),
                ('jurisdiction_expanded', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Auto-calculated: jurisdiction expanded by 1km buffer', null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'department',
                'ordering': ['name'],
            },
        ),
    ]
