# Generated by Django 5.2 on 2025-04-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code_department', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('type_department', models.CharField(choices=[('Bomberos', 'firefighters'), ('Policia', 'police')])),
                ('name_department', models.CharField(max_length=50)),
                ('jurisdiction', models.JSONField()),
                ('city_center_lat', models.FloatField()),
                ('city_center_lon', models.FloatField()),
                ('phone', models.BigIntegerField()),
            ],
        ),
    ]
